---
title: "Homework 6"
author: Nikhita Damaraju
output: github_document
---

This is my solution to Homework 6.

Library imports 

```{r settings, message = FALSE} 
library(tidyverse)
library(dplyr)
library(stringr)
library(ggplot2)


theme_set(theme_bw() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d

# setting seed value
set.seed(1)
```

## Problem 1

```{r message = FALSE}
homicide_df = 
  read_csv('./datasets/homicide-data.csv')
```



## Problem 2

```{r message = FALSE}
weight_df = 
  read_csv('./datasets/birthweight.csv')
```

## Problem 3

Reading data

```{r message = FALSE}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

